### PR TITLE
Support using a pem file in addition to a p12.

### PR DESCRIPTION
**Pull request by jonhyman**
We have some customers who have pem files for their certificates instead of their p12 files, it would be nice to support both.

### CODE REVIEW

**Comment by jonhyman** [comment]
Hm. It looks like adding Gemfile.lock might have caused Travis to fail? The specs all pass locally for me, I do not know about the CI setup.

**Comment by adamvduke** [comment]
Hi @jonhyman,

Thanks for taking time to add support for this. We leave the Gemfile.lock out of the repo intentionally based on this post http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/. I think Travis will re-run if you remove that file from your commit and force push your branch.

**Comment by jonhyman** [comment]
Thanks for the context. I updated, looks like we're good now.

**Comment by adamvduke** [comment]
I pushed a new version, 0.5.0, to rubygems.

🍻

**Comment by jonhyman** [comment]
Thank you!

**Pull request merged**
