### PR TITLE
Intermediate certificate support for package signature

### PR DESCRIPTION
**Pull request by kyle30312**
For #6, ability to add extra cert to the PKCS7 signature, to support
Apple WWDR Intermediate Certificate renewal, per
https://developer.apple.com/support/certificates/expiration/

Pass path to AppleWWDRCA.cer file in extra_certificate parameter.
Old intermediate cert expires 02/14/16; new one expires 02/07/23
per https://www.apple.com/certificateauthority/

### CODE REVIEW

**Comment by adamvduke** [comment]
Looks awesome @kyle30312! Thanks.

**Comment by adamvduke** [comment]
I released a new version based on your change. :beers:

**Comment by kyle30312** [comment]
Super - thanks for the quick turnaround!

On Wed, Jan 27, 2016 at 12:09 PM, Adam Duke <notifications@github.com>
wrote:

> I released a new version based on your change. [image: :beers:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SymmetricInfinity/push_package/pull/7#issuecomment-175749598>
> .
>



-- 
~ Kyle Rogers ~ http://twitter.com/kyrogers ~

**Comment by adamvduke** [comment]
@kyle30312 I just noticed that you work for Turner Broadcasting, do you mind letting me know what properties use this gem? I'm just personally curious. If it shouldn't be public info you can message me on Twitter @adamvduke. :)

**Pull request merged**
